<%@ Page Title="" Language="C#" MasterPageFile="~/SilkTheory.Master" AutoEventWireup="true" CodeBehind="Admin.aspx.cs" Inherits="FinalProject_WA.Admin" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="Styles/main.css" rel="stylesheet" type="text/css" />
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <h2 class="section-title">🛠 Admin - Product Management</h2>

        <div class="cart-summary">
            <asp:Button ID="btnGoToUserEdit" runat="server" Text="User Management" CssClass="btn" OnClick="btnGoToUserEdit_Click" />
            <asp:Button ID="btnGotToOrder" runat="server" Text="Order History" CssClass="btn" OnClick="btnGoToOrder_Click" />
        </div>

        <div class="card" style="margin-top:30px">
            <h4 class="section-title" style="font-size:20px;margin-bottom:20px">Add New Product</h4>

            <asp:FormView ID="fvAddProduct" runat="server" DefaultMode="Insert"
                OnItemInserting="fvAddProduct_ItemInserting"
                CssClass="auth-form"
                OnPageIndexChanging="fvAddProduct_PageIndexChanging">

                <InsertItemTemplate>
                    <label>Product Name:</label>
                    <asp:TextBox ID="txtProductName" runat="server" CssClass="form-control" /><br />

                    <label>Price (RM):</label>
                    <asp:TextBox ID="txtPrice" runat="server" CssClass="form-control" /><br />

                    <label>Upload Image:</label>
                    <asp:FileUpload ID="fuImage" runat="server" CssClass="form-control" /><br />

                    <label>Category:</label>
                    <asp:DropDownList ID="ddlCategory" runat="server"
                        DataSourceID="SqlCategories"
                        DataTextField="CategoryName"
                        DataValueField="CategoryID"
                        CssClass="form-control" /><br /><br />

                    <asp:Button ID="btnInsert" runat="server" CommandName="Insert" Text="Insert Product" CssClass="btn" />
                </InsertItemTemplate>
            </asp:FormView>
        </div>

        <div class="card" style="margin-top:50px">
            <h4 class="section-title" style="font-size:20px;margin-bottom:20px">Current Product List</h4>

            <asp:GridView ID="gvProducts" runat="server" DataSourceID="SqlProductList"
                AutoGenerateColumns="False"
                CssClass="table"
                DataKeyNames="ProductID"
                AutoGenerateEditButton="True"
                AutoGenerateDeleteButton="True">

                <Columns>
                    <asp:BoundField DataField="ProductID" HeaderText="ID" ReadOnly="True" />
                    <asp:BoundField DataField="ProductName" HeaderText="Name" />
                    <asp:BoundField DataField="Price" HeaderText="Price (RM)" DataFormatString="{0:F2}" />
                    <asp:ImageField DataImageUrlField="ImageUrl" HeaderText="Image">
                        <ControlStyle Width="80px" Height="80px" />
                    </asp:ImageField>
                    <asp:BoundField DataField="CategoryName" HeaderText="Category" />
                </Columns>
            </asp:GridView>
        </div>

        <asp:SqlDataSource ID="SqlCategories" runat="server"
            ConnectionString="<%$ ConnectionStrings:SilkTheoryConnectionString %>"
            SelectCommand="SELECT CategoryID, CategoryName FROM Categories" />

        <asp:SqlDataSource ID="SqlProductList" runat="server"
            ConnectionString="<%$ ConnectionStrings:SilkTheoryConnectionString %>"
            SelectCommand="SELECT P.ProductID, P.ProductName, P.Price, P.ImageUrl, C.CategoryName 
                           FROM Products P 
                           INNER JOIN Categories C ON P.CategoryID = C.CategoryID 
                           WHERE P.IsDeleted = 0"
            UpdateCommand="UPDATE Products SET ProductName = @ProductName, Price = @Price WHERE ProductID = @ProductID"
            DeleteCommand="UPDATE Products SET IsDeleted = 1 WHERE ProductID = @ProductID">
            <UpdateParameters>
                <asp:Parameter Name="ProductName" Type="String" />
                <asp:Parameter Name="Price" Type="Decimal" />
                <asp:Parameter Name="ProductID" Type="Int32" />
            </UpdateParameters>
            <DeleteParameters>
                <asp:Parameter Name="ProductID" Type="Int32" />
            </DeleteParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>