<%@ Page Title="" Language="C#" MasterPageFile="~/SilkTheory.Master" AutoEventWireup="true" CodeBehind="AdminUserEdit.aspx.cs" Inherits="FinalProject_WA.AdminUserEdit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="Styles/main.css" rel="stylesheet" type="text/css" />
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <h2 class="section-title">👥 Admin - User Management</h2>

        <div class="cart-summary">
            <asp:Button ID="btnBackToAdmin" runat="server" Text="← Back to Admin" CssClass="btn" OnClick="btnBackToAdmin_Click" />
        </div>

        <asp:Label ID="lblError" runat="server" Visible="false" CssClass="auth-message error" />

        <div class="card" style="margin-top:30px">
            <asp:GridView ID="gvUsers" runat="server" DataSourceID="SqlUsers"
                AutoGenerateColumns="False"
                CssClass="table"
                DataKeyNames="UserId"
                AutoGenerateEditButton="True"
                AutoGenerateDeleteButton="True"
                OnRowEditing="gvUsers_RowEditing"
                OnRowCancelingEdit="gvUsers_RowCancelingEdit"
                OnRowUpdating="gvUsers_RowUpdating"
                OnRowDeleting="gvUsers_RowDeleting">

                <Columns>
                    <asp:BoundField DataField="UserId" HeaderText="User ID" ReadOnly="True" />
                    <asp:BoundField DataField="Username" HeaderText="Username" />
                    <asp:BoundField DataField="Email" HeaderText="Email" />
                    <asp:BoundField DataField="Role" HeaderText="Role" />
                </Columns>
            </asp:GridView>
        </div>

        <asp:SqlDataSource ID="SqlUsers" runat="server"
            ConnectionString="<%$ ConnectionStrings:SilkTheoryConnectionString %>"
            SelectCommand="SELECT UserId, Username, Email, Role FROM Users"
            UpdateCommand="updateUser"
            UpdateCommandType="StoredProcedure"
            DeleteCommand="DeleteUserById"
            DeleteCommandType="StoredProcedure">

            <UpdateParameters>
                <asp:Parameter Name="UserId" Type="Int32" />
                <asp:Parameter Name="Username" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="Role" Type="String" />
            </UpdateParameters>

            <DeleteParameters>
                <asp:Parameter Name="UserId" Type="Int32" />
            </DeleteParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>
